"use client";

import * as dotenv from 'dotenv'
dotenv.config()
import Head from "next/head";
import { Inter } from "next/font/google";
import { MongoClient } from "mongodb";
import styles from "../styles/Home.module.css";
import user from "../composants/composants2";

const inter = Inter({ subsets: ["latin"] });
// const client = new MongoClient(process.env.URI);
export default function Home() {
  return (
    <>
      <Head>
        <title>projet de groupe</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
        <div className={styles.description}>
          <div className={styles.margin}>
            
          </div>
        </div>
    </>
  );
}
